### ISSUE TITLE
Устаревший метод получения информации о клане

### ISSUE THREAD

**Issue by REDMONDS** [akeinhell/MSFC#25]
Апрель 2015

Методы Кланы, Данные клана, Данные участника клана API World of Tanks будут отключены. Пожалуйста, используйте методы из API Wargaming.net Кланы, Данные клана, Данные участника клана.
Источник: https://ru.wargaming.net/developers/documentation/guide/deprecated-features/

P.S:. В ближайшем обновлении метод доработают.

![anuewbm](https://cloud.githubusercontent.com/assets/6460267/6478755/cf7bef36-c24a-11e4-9f60-bca50c7496c4.png)

**Comment by akeinhell** [comment]
```
app/Clanstats/Modules/Cron$ cat -n Cron.php | grep "clan->info"
   137	        if ($info = self::$api->clan->info(array('clan_id' => implode(',', $clans)))) {
```
